### ISSUE TITLE
error in running

### ISSUE THREAD

**Issue by Ayush0601** [csanuragjain/recorder#1]
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at com.github.sarxos.webcam.Webcam.<clinit>(Webcam.java:20)
        at WebcamCapture.main(WebcamCapture.java:13)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more

**Comment by Ayush0601** [comment]
can you please help me to solve it
